name: Docker Image CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to the container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:latest

      - name: Cleanup older images
        run: |
          IMAGE_NAME=${{ secrets.REGISTRY_URL }}/${{ github.repository }}
          OLD_IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep $IMAGE_NAME | sort -r | tail -n +6)
          if [ -n "$OLD_IMAGES" ]; then
            echo "Removing older images:"
            echo "$OLD_IMAGES" | xargs -I {} docker rmi {}
          else
            echo "No older images to remove."
          fi
