name: Docker Image CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: DOCKER_CLI='docker' docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:latest

      - name: Cleanup older images
        run: |
          IMAGE_NAME=${{ secrets.REGISTRY_URL }}/${{ github.repository }}
          OLD_IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep $IMAGE_NAME | sort -r | tail -n +6)
          if [ -n "$OLD_IMAGES" ]; then
            echo "Removing older images:"
            echo "$OLD_IMAGES" | xargs -I {} docker rmi {}
          else
            echo "No older images to remove."
          fi
